server: 
  port: 18888
  address: 0.0.0.0
  servlet:
    context-path: /charge
liquibase: 
  enabled: true 
  change-log: classpath:/dbChangeLog/changelog-master.xml
spring: 
  jackson: 
    date-format: "yyyy-MM-dd HH:mm:ss" 
    time-zone: GMT+8
  application: 
    name: EUnionPayDirectServer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-2zemlbv21u27044s3xo.mysql.rds.aliyuncs.com:3306/jfshare_office_pre?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true
    username: jfshare_off_dev
    password: Jfshare123
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20 
logging:
  config:
   classpath:logback-boot.xml
