enableApi: true
server: 
  port: 18888
  address: 0.0.0.0
  servlet:
    context-path: /mvp
spring: 
  liquibase: 
    enabled: true 
    change-log: classpath:/dbChangeLog/changelog-master.xml
  jackson: 
    date-format: "yyyy-MM-dd HH:mm:ss" 
    time-zone: GMT+8
  application: 
    name: JfshareMvpServerPro
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-2zemlbv21u27044s3xo.mysql.rds.aliyuncs.com:3306/db_jfshare_mvp_dev?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true
    username: jfshare_off_dev
    password: Jfshare123
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    host: 120.24.153.155
    port: 16379
    database: 0
    password: Jfshare888
    pool:
      max-idle:  8
      min-idle:  0
      max-active:  8
      max-wait:  -1
  rabbitmq:
    host: 39.106.147.35
    port: 5672
    username: admin
    password: admin
  data:
    elasticsearch:
      cluster-nodes: 39.107.230.91:9300
      repositories:
        enabled: true
mybatis:
  typeAliasesPackage: com.jfshare.mvp.server.mapper
  mapperLocations: classpath:/mybatis/sqlmap/**/*.xml 
  configLocation: classpath:/mybatis/mybatis-config.xml 
logging:
  config:
   classpath:logback-boot.xml
